dataset_root: /workspace/SlowFastSign/dataset/phoenix2014-30percent-labeled/phoenix-2014-multisigner
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-30percent-labeled-groundtruth
